export const projects = [
  {
    id: 1,
    img: "https://media.giphy.com/media/1YHfCEw7pDVgwDBmTY/giphy.gif",
    title: "Reverie E-commerce",
    description: `An E-commerce website to sell luxury watches. This project was built using React, Airtable, Auth0, Stripe with features such as product listing, product details, shopping cart, user authentication with Auth0 and checkout with Stripe payment.`,
    tags: ["React", "Airtable", "Auth0", "Stripe", "Tailwind"],
    liveLink: "https://reverie-ecommerce.netlify.app/",
    ghLink: "https://github.com/mid9coward/Ecommerce-Reactjs",
  },

  {
    id: 2,
    img: "https://media.giphy.com/media/pNtoZaNVF0VtpKEbRX/giphy.gif",
    title: "Vietnam Travel Website",
    description: `A travel website where visitors can get detailed information, latest news & useful tips on visas, destinations & what to do in Vietnam. Developed using the ReactJS and styled using TailwindCSS.`,
    tags: ["React", "Tailwind"],
    liveLink: "https://vietravel.netlify.app/",
    ghLink: "https://github.com/mid9coward/Vietravel",
  },
  {
    id: 3,
    img: "https://user-images.githubusercontent.com/88967412/235461407-c9c4eb3d-b488-404a-968c-ad10d5153253.gif",
    title: "Airbnb Clone",
    description: `Full Stack Airbnb Clone with Next.js 13 Tailwind-css, Prisma, MongoDB, NextAuth, Framer-motionSocial, Login (Google and Facebook), Image upload, Cloudinary CDN, Location selection, Map component, Country autocomplete, Fetching listings with server components.`,
    tags: ["React", "Nextjs", "Tailwind", "MongoDB", "NextAuth"],
    liveLink: "https://coderschool-final.vercel.app/",
    ghLink: "https://github.com/mid9coward/Airbnb-clone-Nextjs",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dyexdgldg/image/upload/v1762748599/macbook_kprsrd.jpg",
    title: "Stock Market Web App",
    description: `AI-powered modern stock market app built with Next.js, Shadcn, Better Auth, and Inngest! Track real-time prices, set personalized alerts, explore company insights, and manage watchlists.`,
    tags: [
      "Nextjs",
      "Better Auth",
      "Shadcn",
      "Inngest",
      "MongoDB",
      "Tailwind",
      "Typescript",
    ],
    liveLink: "https://signalist-stock-tracker-app-ochre.vercel.app/",
    ghLink: "https://github.com/mid9coward/signalist_stock-tracker-app",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dyexdgldg/image/upload/v1762748599/stockmarket_psjkyd.webp",
    title: "Apple Mac Website",
    description: `Apple-style 3D website built with React, Three.js, GSAP, and TailwindCSS! Showcase products in immersive 3D scenes, scroll-animated models, and pinned sections.`,
    tags: ["React", "Gsap", "Threejs", "Tailwind", "Zustand", "Javascript"],
    liveLink: "https://macbook-gsap-app-five.vercel.app/",
    ghLink: "https://github.com/mid9coward/macbook_gsap_app",
  },
];
